[package]
name = "emmylua_ls"
version = "0.3.0"
edition = "2021"

[dependencies]
code_analysis = { path = "../code_analysis" }
emmylua_parser = { path = "../emmylua_parser" }
meta_text = { path = "../meta_text" }

lsp-server.workspace = true
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
lsp-types.workspace = true
log.workspace = true
fern.workspace = true
chrono.workspace = true
notify.workspace = true
tokio-util.workspace = true
rowan.workspace = true
emmylua_codestyle.workspace = true
walkdir.workspace = true
structopt.workspace = true
