[package]
name = "emmylua_ls"
version = "0.2.4"
edition = "2021"

[dependencies]
lsp-server = "0.7.7"
tokio = { version = "1", features = ["full"] }

code_analysis = { path = "../code_analysis" }
emmylua_parser = { path = "../emmylua_parser" }
meta_text = { path = "../meta_text" }
serde.workspace = true
serde_json.workspace = true
lsp-types.workspace = true
log.workspace = true
fern.workspace = true
chrono.workspace = true
notify.workspace = true
tokio-util.workspace = true
rowan.workspace = true
emmylua_codestyle.workspace = true
walkdir.workspace = true
structopt.workspace = true