[workspace]
resolver = "2"
members = [
    "crates/*",
]

[workspace.dependencies]
serde = { version = "1.0.210", features = ["derive"] } 
serde_json = "1.0.128"
rowan = { version = "0.16" }
notify = { version = "6.1.1", features = ["serde"] }
lsp-types = { version = "0.97.0", features = ["proposed"]}
schemars = "0.8.21"
regex = "1"
internment = { version = "0.8", features = ["arc"] }
