[package]
name = "schema_json_gen"
version = "0.1.0"
edition = "2021"

[dependencies]
code_analysis = { path = "../code_analysis" }
schemars.workspace = true
serde.workspace = true
serde_json.workspace = true
lsp-types.workspace = true
