[package]
name = "meta_text"
version = "0.1.0"
edition = "2021"

[dependencies]
glob = "0.3"

rust-i18n.workspace = true
log.workspace = true
serde_yml.workspace = true

[package.metadata.i18n]
available-locales = ["en", "zh_CN", "zh_HK", "zh_TW"]
default-locale = "en"