name: "Upload to Cachix"

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build-and-cache:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Install Nix
      uses: cachix/install-nix-action@v22
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
    
    - name: Set version
      run: |
        echo "current ref ${{ github.ref }}"
        cargo run -p edit_version -- ${{ github.ref }}
    
    - name: Setup Cachix
      uses: cachix/cachix-action@v12
      with:
        name: emmylua-analyzer
        authToken: '${{ secrets.CACHIX }}'
        pushFilter: ""
        
    - name: Build and cache dependencies
      run: |
        if [ -f flake.nix ]; then
          nix build
        else
          nix-build
        fi

